[Service]
# Run the daemon unconfined to avoid SELinux denials on the Nix store binaries.
SELinuxContext=system_u:system_r:unconfined_service_t:s0
ExecStart=
ExecStart=/usr/bin/nix-daemon-wrapper.sh --daemon
